### PR TITLE
Add JEDI geoval variables for ozone data

### PR DESCRIPTION
**Pull request by emilyhcliu**
The following two types of variables are added:
(1) geoval variables required by JEDI for ozone data
(2) ozone observation QC flag (from data provider)

### CODE REVIEW

**Comment by emilyhcliu** [comment]
Test performed:
(1) create OMPSNP and OMPSTC global data from this feature branch (feature/jedi-gdas-ozone) for 2020110112.
(2) Test results for OMPSNP (nadir profile) and OMPSTC (total column) --- tests passed!

OMPSNP NPP
```
Test     : Vector difference between reference and computed: OzoneLayer nobs= 5214 Min=-0.0756073, Max=0.0456035, RMS=0.00422021
```

OPMPSTC NPP
```
Test     : Vector difference between reference and computed: OzoneLayer nobs= 6296 Min=-0.0533978, Max=0.0160388, RMS=0.00260001
```

**Comment by emilyhcliu** [comment]
Working on OMI test ...

**Comment by emilyhcliu** [comment]
Test performed for OMI AURA --- test passed

```
Test     : Vector difference between reference and computed: OzoneLayer nobs= 2469 Min=-0.0507967, Max=0.00570537, RMS=0.002628
```

**Review by fcvdb — APPROVED** [review]
The changes look good to me. Thanks Emily.

**Review by CoryMartin-NOAA — APPROVED** [review]

**Pull request merged**
